---
- name: command
  hosts: ios
  gather_facts: false
#  connection: network_cli
#  user: febry
  vars:
    year: "{{ lookup('pipe', 'date +%Y') }}"
    month: "{{ lookup('pipe', 'date +%m') }}"
    date: "{{ lookup('pipe', 'date +%d') }}"

  tasks:
   - name: backup switch
     ios_config:
       backup: yes
       backup_options:
         dir_path: /var/awx/{{ year }}/{{ month }}/{{ date }}
     register: output
     when: ansible_network_os == 'ios'
